# Name of your application. Used to uniquely configure containers.
service: staging-app

# Name of the container image.
image: locomotivecms/staging-app

# Deploy to these servers.
servers:  
  web:
    hosts:
      - 172.232.44.53
    
builder:
  arch: amd64

proxy:
  ssl: true
  hosts: [""]
  tls_on_demand_url: "http://staging-app-web-latest:3000/locomotive/api/allowed_host"
  app_port: 3000
  forward_headers: true
  healthcheck: 
    interval: 3
    timeout: 60

# Credentials for your image host.
registry:
  server: ghcr.io
  username: did
  password:
    - DOCKER_REGISTRY_TOKEN

accessories:
  # NOTE: Having mongodb requires a DO Droplet with at the very least 2GiB
  # mongodb:
  #   image: mongodb/mongodb-community-server:7.0.12-ubuntu2204
  #   roles:
  #     - web
  #   env:
  #     secret:
  #       - MONGODB_INITDB_ROOT_USERNAME
  #       - MONGODB_INITDB_ROOT_PASSWORD
  #   volumes:
  #     - /var/lib/mongodb-config:/data/configdb
  #     - /var/lib/mongodb:/data/db
  #   options:
  #     network: "private"

  redis:
    image: redis:7.0
    roles:
      - web
    volumes:
      - /var/lib/redis:/data
    cmd: "redis-server --appendonly no --maxmemory 128mb --maxmemory-policy allkeys-lru"
    
# Inject ENV variables into containers (secrets come from .kamal/secrets).
# # Remember to run `kamal env push` after making changes!
env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    LANG: en_US.UTF-8
    NEW_RELIC_LOG: stdout
    RACK_ENV: production
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: enabled
    RAILS_SERVE_STATIC_FILES: enabled 
    REDIS_URL: "redis://staging-app-redis:6379/0"
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - DRAGONFLYAPP_URL
    - DRAGONFLY_SECRET_KEY
    - MONGODB_URI
    - NEW_RELIC_LICENSE_KEY
    - S3_ASSET_HOST_URL
    - S3_BUCKET
    - S3_BUCKET_REGION
    - S3_KEY_ID
    - S3_SECRET_KEY
    - SCOUT_APM_KEY
    - SENDGRID_USERNAME
    - SENDGRID_PASSWORD
    # - MONGODB_INITDB_ROOT_USERNAME
    # - MONGODB_INITDB_ROOT_PASSWORD
